// This file was automatically generated by the Dapper.SimpleCRUD T4 Template
// Do not make changes directly to this file - edit the template instead
// 
// The following connection settings were used to generate this file
// 
//     Connection String Name: `SqlServer`
//     Provider:               `System.Data.SqlClient`
//     Connection String:      `Server=heavencloud.mine.nu\MSSQLHEAVEN,1433;Database=demoretail;User Id=HeavenAdmin;MultipleActiveResultSets=True;Password=******;`
//     Include Views:          `True`

using Sequel;
using Heaven.Data;

namespace Heaven.Data
{
	public partial interface IMLUpdatePendingRepository : IRepository<MLUpdatePending> { }

	public partial class MLUpdatePendingRepository : Repository<MLUpdatePending>
	{
		public MLUpdatePendingRepository(IDbContext dbContext, ISqlMapper<MLUpdatePending> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IVistaCajaAsientosRepository : IRepository<VistaCajaAsientos> { }

	public partial class VistaCajaAsientosRepository : Repository<VistaCajaAsientos>
	{
		public VistaCajaAsientosRepository(IDbContext dbContext, ISqlMapper<VistaCajaAsientos> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IStockReservadoRepository : IRepository<StockReservado> { }

	public partial class StockReservadoRepository : Repository<StockReservado>
	{
		public StockReservadoRepository(IDbContext dbContext, ISqlMapper<StockReservado> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IListaPreciosItemsRepository : IRepository<ListaPreciosItems> { }

	public partial class ListaPreciosItemsRepository : Repository<ListaPreciosItems>
	{
		public ListaPreciosItemsRepository(IDbContext dbContext, ISqlMapper<ListaPreciosItems> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IConfiguracionesPUISRepository : IRepository<ConfiguracionesPUIS> { }

	public partial class ConfiguracionesPUISRepository : Repository<ConfiguracionesPUIS>
	{
		public ConfiguracionesPUISRepository(IDbContext dbContext, ISqlMapper<ConfiguracionesPUIS> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IColumnasSettingGrillaRepository : IRepository<ColumnasSettingGrilla> { }

	public partial class ColumnasSettingGrillaRepository : Repository<ColumnasSettingGrilla>
	{
		public ColumnasSettingGrillaRepository(IDbContext dbContext, ISqlMapper<ColumnasSettingGrilla> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IIRSABranchRepository : IRepository<IRSABranch> { }

	public partial class IRSABranchRepository : Repository<IRSABranch>
	{
		public IRSABranchRepository(IDbContext dbContext, ISqlMapper<IRSABranch> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IServicioTecnicoIdStIdTipoTrabajoRepository : IRepository<ServicioTecnicoIdStIdTipoTrabajo> { }

	public partial class ServicioTecnicoIdStIdTipoTrabajoRepository : Repository<ServicioTecnicoIdStIdTipoTrabajo>
	{
		public ServicioTecnicoIdStIdTipoTrabajoRepository(IDbContext dbContext, ISqlMapper<ServicioTecnicoIdStIdTipoTrabajo> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IConfiguracionesPUISItemsRepository : IRepository<ConfiguracionesPUISItems> { }

	public partial class ConfiguracionesPUISItemsRepository : Repository<ConfiguracionesPUISItems>
	{
		public ConfiguracionesPUISItemsRepository(IDbContext dbContext, ISqlMapper<ConfiguracionesPUISItems> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IMLNotificacionesRepository : IRepository<MLNotificaciones> { }

	public partial class MLNotificacionesRepository : Repository<MLNotificaciones>
	{
		public MLNotificacionesRepository(IDbContext dbContext, ISqlMapper<MLNotificaciones> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IPromocionesRepository : IRepository<Promociones> { }

	public partial class PromocionesRepository : Repository<Promociones>
	{
		public PromocionesRepository(IDbContext dbContext, ISqlMapper<Promociones> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IMLMensajesEnviadosRepository : IRepository<MLMensajesEnviados> { }

	public partial class MLMensajesEnviadosRepository : Repository<MLMensajesEnviados>
	{
		public MLMensajesEnviadosRepository(IDbContext dbContext, ISqlMapper<MLMensajesEnviados> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IPromocionesArticulosRepository : IRepository<PromocionesArticulos> { }

	public partial class PromocionesArticulosRepository : Repository<PromocionesArticulos>
	{
		public PromocionesArticulosRepository(IDbContext dbContext, ISqlMapper<PromocionesArticulos> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IDepositosRepository : IRepository<Depositos> { }

	public partial class DepositosRepository : Repository<Depositos>
	{
		public DepositosRepository(IDbContext dbContext, ISqlMapper<Depositos> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IGarantiasExtendidasProductoRepository : IRepository<GarantiasExtendidasProducto> { }

	public partial class GarantiasExtendidasProductoRepository : Repository<GarantiasExtendidasProducto>
	{
		public GarantiasExtendidasProductoRepository(IDbContext dbContext, ISqlMapper<GarantiasExtendidasProducto> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IMLTemasRespuestasRepository : IRepository<MLTemasRespuestas> { }

	public partial class MLTemasRespuestasRepository : Repository<MLTemasRespuestas>
	{
		public MLTemasRespuestasRepository(IDbContext dbContext, ISqlMapper<MLTemasRespuestas> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IPaquetesMonedasRepository : IRepository<PaquetesMonedas> { }

	public partial class PaquetesMonedasRepository : Repository<PaquetesMonedas>
	{
		public PaquetesMonedasRepository(IDbContext dbContext, ISqlMapper<PaquetesMonedas> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IAccesosUsuarioRepository : IRepository<AccesosUsuario> { }

	public partial class AccesosUsuarioRepository : Repository<AccesosUsuario>
	{
		public AccesosUsuarioRepository(IDbContext dbContext, ISqlMapper<AccesosUsuario> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IMonedasRepository : IRepository<Monedas> { }

	public partial class MonedasRepository : Repository<Monedas>
	{
		public MonedasRepository(IDbContext dbContext, ISqlMapper<Monedas> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IVistaClientesComercioRepository : IRepository<VistaClientesComercio> { }

	public partial class VistaClientesComercioRepository : Repository<VistaClientesComercio>
	{
		public VistaClientesComercioRepository(IDbContext dbContext, ISqlMapper<VistaClientesComercio> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IMLOrdenesFacturadasRepository : IRepository<MLOrdenesFacturadas> { }

	public partial class MLOrdenesFacturadasRepository : Repository<MLOrdenesFacturadas>
	{
		public MLOrdenesFacturadasRepository(IDbContext dbContext, ISqlMapper<MLOrdenesFacturadas> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IMLUsuariosucursalesRepository : IRepository<MLUsuariosucursales> { }

	public partial class MLUsuariosucursalesRepository : Repository<MLUsuariosucursales>
	{
		public MLUsuariosucursalesRepository(IDbContext dbContext, ISqlMapper<MLUsuariosucursales> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IRedondeosRepository : IRepository<Redondeos> { }

	public partial class RedondeosRepository : Repository<Redondeos>
	{
		public RedondeosRepository(IDbContext dbContext, ISqlMapper<Redondeos> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IDespachosAsignadosRepository : IRepository<DespachosAsignados> { }

	public partial class DespachosAsignadosRepository : Repository<DespachosAsignados>
	{
		public DespachosAsignadosRepository(IDbContext dbContext, ISqlMapper<DespachosAsignados> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IVistaPedidosClientesRepository : IRepository<VistaPedidosClientes> { }

	public partial class VistaPedidosClientesRepository : Repository<VistaPedidosClientes>
	{
		public VistaPedidosClientesRepository(IDbContext dbContext, ISqlMapper<VistaPedidosClientes> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface INombreImpuestosRepository : IRepository<NombreImpuestos> { }

	public partial class NombreImpuestosRepository : Repository<NombreImpuestos>
	{
		public NombreImpuestosRepository(IDbContext dbContext, ISqlMapper<NombreImpuestos> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IVistaItemsWebb2bRepository : IRepository<VistaItemsWebb2b> { }

	public partial class VistaItemsWebb2bRepository : Repository<VistaItemsWebb2b>
	{
		public VistaItemsWebb2bRepository(IDbContext dbContext, ISqlMapper<VistaItemsWebb2b> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IStockCriticoRepository : IRepository<StockCritico> { }

	public partial class StockCriticoRepository : Repository<StockCritico>
	{
		public StockCriticoRepository(IDbContext dbContext, ISqlMapper<StockCritico> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IRubroGruposRepository : IRepository<RubroGrupos> { }

	public partial class RubroGruposRepository : Repository<RubroGrupos>
	{
		public RubroGruposRepository(IDbContext dbContext, ISqlMapper<RubroGrupos> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IDepositosNivelesRepository : IRepository<DepositosNiveles> { }

	public partial class DepositosNivelesRepository : Repository<DepositosNiveles>
	{
		public DepositosNivelesRepository(IDbContext dbContext, ISqlMapper<DepositosNiveles> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IVistaServicioTecnicoInsumosRepository : IRepository<VistaServicioTecnicoInsumos> { }

	public partial class VistaServicioTecnicoInsumosRepository : Repository<VistaServicioTecnicoInsumos>
	{
		public VistaServicioTecnicoInsumosRepository(IDbContext dbContext, ISqlMapper<VistaServicioTecnicoInsumos> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IDepositosUbicacionesRepository : IRepository<DepositosUbicaciones> { }

	public partial class DepositosUbicacionesRepository : Repository<DepositosUbicaciones>
	{
		public DepositosUbicacionesRepository(IDbContext dbContext, ISqlMapper<DepositosUbicaciones> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface ITransportesRepository : IRepository<Transportes> { }

	public partial class TransportesRepository : Repository<Transportes>
	{
		public TransportesRepository(IDbContext dbContext, ISqlMapper<Transportes> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IVistaTrasladoArticulosRepository : IRepository<VistaTrasladoArticulos> { }

	public partial class VistaTrasladoArticulosRepository : Repository<VistaTrasladoArticulos>
	{
		public VistaTrasladoArticulosRepository(IDbContext dbContext, ISqlMapper<VistaTrasladoArticulos> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IOrdenesHistorialRepository : IRepository<OrdenesHistorial> { }

	public partial class OrdenesHistorialRepository : Repository<OrdenesHistorial>
	{
		public OrdenesHistorialRepository(IDbContext dbContext, ISqlMapper<OrdenesHistorial> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IRemitoTercerizadoItemPendienteRepository : IRepository<RemitoTercerizadoItemPendiente> { }

	public partial class RemitoTercerizadoItemPendienteRepository : Repository<RemitoTercerizadoItemPendiente>
	{
		public RemitoTercerizadoItemPendienteRepository(IDbContext dbContext, ISqlMapper<RemitoTercerizadoItemPendiente> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IDepositosArticulosUbicacionesRepository : IRepository<DepositosArticulosUbicaciones> { }

	public partial class DepositosArticulosUbicacionesRepository : Repository<DepositosArticulosUbicaciones>
	{
		public DepositosArticulosUbicacionesRepository(IDbContext dbContext, ISqlMapper<DepositosArticulosUbicaciones> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IFirmaCertificadosRepository : IRepository<FirmaCertificados> { }

	public partial class FirmaCertificadosRepository : Repository<FirmaCertificados>
	{
		public FirmaCertificadosRepository(IDbContext dbContext, ISqlMapper<FirmaCertificados> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface ITarjetasCarteraRepository : IRepository<TarjetasCartera> { }

	public partial class TarjetasCarteraRepository : Repository<TarjetasCartera>
	{
		public TarjetasCarteraRepository(IDbContext dbContext, ISqlMapper<TarjetasCartera> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface ITareasTipoRepository : IRepository<TareasTipo> { }

	public partial class TareasTipoRepository : Repository<TareasTipo>
	{
		public TareasTipoRepository(IDbContext dbContext, ISqlMapper<TareasTipo> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IVistaItemsWebheavenymcommerceRepository : IRepository<VistaItemsWebheavenymcommerce> { }

	public partial class VistaItemsWebheavenymcommerceRepository : Repository<VistaItemsWebheavenymcommerce>
	{
		public VistaItemsWebheavenymcommerceRepository(IDbContext dbContext, ISqlMapper<VistaItemsWebheavenymcommerce> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IAutorizacionDescuentoRepository : IRepository<AutorizacionDescuento> { }

	public partial class AutorizacionDescuentoRepository : Repository<AutorizacionDescuento>
	{
		public AutorizacionDescuentoRepository(IDbContext dbContext, ISqlMapper<AutorizacionDescuento> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface ITareasidTipoidUsuarioRepository : IRepository<TareasidTipoidUsuario> { }

	public partial class TareasidTipoidUsuarioRepository : Repository<TareasidTipoidUsuario>
	{
		public TareasidTipoidUsuarioRepository(IDbContext dbContext, ISqlMapper<TareasidTipoidUsuario> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IVistaVentasPorVendedorRepository : IRepository<VistaVentasPorVendedor> { }

	public partial class VistaVentasPorVendedorRepository : Repository<VistaVentasPorVendedor>
	{
		public VistaVentasPorVendedorRepository(IDbContext dbContext, ISqlMapper<VistaVentasPorVendedor> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IPaisesRepository : IRepository<Paises> { }

	public partial class PaisesRepository : Repository<Paises>
	{
		public PaisesRepository(IDbContext dbContext, ISqlMapper<Paises> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IUsuarioQueVeCtaRepository : IRepository<UsuarioQueVeCta> { }

	public partial class UsuarioQueVeCtaRepository : Repository<UsuarioQueVeCta>
	{
		public UsuarioQueVeCtaRepository(IDbContext dbContext, ISqlMapper<UsuarioQueVeCta> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface ITarjetasLotesRepository : IRepository<TarjetasLotes> { }

	public partial class TarjetasLotesRepository : Repository<TarjetasLotes>
	{
		public TarjetasLotesRepository(IDbContext dbContext, ISqlMapper<TarjetasLotes> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IHCOrdersRepository : IRepository<HCOrders> { }

	public partial class HCOrdersRepository : Repository<HCOrders>
	{
		public HCOrdersRepository(IDbContext dbContext, ISqlMapper<HCOrders> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IDescuentosAcumuladosRepository : IRepository<DescuentosAcumulados> { }

	public partial class DescuentosAcumuladosRepository : Repository<DescuentosAcumulados>
	{
		public DescuentosAcumuladosRepository(IDbContext dbContext, ISqlMapper<DescuentosAcumulados> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IComprobantesCAERepository : IRepository<ComprobantesCAE> { }

	public partial class ComprobantesCAERepository : Repository<ComprobantesCAE>
	{
		public ComprobantesCAERepository(IDbContext dbContext, ISqlMapper<ComprobantesCAE> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface ITarjetasIncluidasEnLoteRepository : IRepository<TarjetasIncluidasEnLote> { }

	public partial class TarjetasIncluidasEnLoteRepository : Repository<TarjetasIncluidasEnLote>
	{
		public TarjetasIncluidasEnLoteRepository(IDbContext dbContext, ISqlMapper<TarjetasIncluidasEnLote> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IDescuentosAcumuladosGrupoRepository : IRepository<DescuentosAcumuladosGrupo> { }

	public partial class DescuentosAcumuladosGrupoRepository : Repository<DescuentosAcumuladosGrupo>
	{
		public DescuentosAcumuladosGrupoRepository(IDbContext dbContext, ISqlMapper<DescuentosAcumuladosGrupo> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IServicioTecnicoRepository : IRepository<ServicioTecnico> { }

	public partial class ServicioTecnicoRepository : Repository<ServicioTecnico>
	{
		public ServicioTecnicoRepository(IDbContext dbContext, ISqlMapper<ServicioTecnico> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IVariablesRepository : IRepository<Variables> { }

	public partial class VariablesRepository : Repository<Variables>
	{
		public VariablesRepository(IDbContext dbContext, ISqlMapper<Variables> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface ISucursalesConfiguracionRepository : IRepository<SucursalesConfiguracion> { }

	public partial class SucursalesConfiguracionRepository : Repository<SucursalesConfiguracion>
	{
		public SucursalesConfiguracionRepository(IDbContext dbContext, ISqlMapper<SucursalesConfiguracion> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface ITarjetasMatrizRepository : IRepository<TarjetasMatriz> { }

	public partial class TarjetasMatrizRepository : Repository<TarjetasMatriz>
	{
		public TarjetasMatrizRepository(IDbContext dbContext, ISqlMapper<TarjetasMatriz> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IAccesosRolesRepository : IRepository<AccesosRoles> { }

	public partial class AccesosRolesRepository : Repository<AccesosRoles>
	{
		public AccesosRolesRepository(IDbContext dbContext, ISqlMapper<AccesosRoles> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IProvinciasRepository : IRepository<Provincias> { }

	public partial class ProvinciasRepository : Repository<Provincias>
	{
		public ProvinciasRepository(IDbContext dbContext, ISqlMapper<Provincias> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IRemitoTercerizadoRepository : IRepository<RemitoTercerizado> { }

	public partial class RemitoTercerizadoRepository : Repository<RemitoTercerizado>
	{
		public RemitoTercerizadoRepository(IDbContext dbContext, ISqlMapper<RemitoTercerizado> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IImpresorasFiscalesRepository : IRepository<ImpresorasFiscales> { }

	public partial class ImpresorasFiscalesRepository : Repository<ImpresorasFiscales>
	{
		public ImpresorasFiscalesRepository(IDbContext dbContext, ISqlMapper<ImpresorasFiscales> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface ICajaArqueoRepository : IRepository<CajaArqueo> { }

	public partial class CajaArqueoRepository : Repository<CajaArqueo>
	{
		public CajaArqueoRepository(IDbContext dbContext, ISqlMapper<CajaArqueo> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IMLMensajesNoLeidosRepository : IRepository<MLMensajesNoLeidos> { }

	public partial class MLMensajesNoLeidosRepository : Repository<MLMensajesNoLeidos>
	{
		public MLMensajesNoLeidosRepository(IDbContext dbContext, ISqlMapper<MLMensajesNoLeidos> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IRemitoTercerizadoItemRepository : IRepository<RemitoTercerizadoItem> { }

	public partial class RemitoTercerizadoItemRepository : Repository<RemitoTercerizadoItem>
	{
		public RemitoTercerizadoItemRepository(IDbContext dbContext, ISqlMapper<RemitoTercerizadoItem> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IComprobantesEncabezadoRepository : IRepository<ComprobantesEncabezado> { }

	public partial class ComprobantesEncabezadoRepository : Repository<ComprobantesEncabezado>
	{
		public ComprobantesEncabezadoRepository(IDbContext dbContext, ISqlMapper<ComprobantesEncabezado> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IMLAConfiguracionesRepository : IRepository<MLAConfiguraciones> { }

	public partial class MLAConfiguracionesRepository : Repository<MLAConfiguraciones>
	{
		public MLAConfiguracionesRepository(IDbContext dbContext, ISqlMapper<MLAConfiguraciones> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IMLEtiquetasPostVentaRepository : IRepository<MLEtiquetasPostVenta> { }

	public partial class MLEtiquetasPostVentaRepository : Repository<MLEtiquetasPostVenta>
	{
		public MLEtiquetasPostVentaRepository(IDbContext dbContext, ISqlMapper<MLEtiquetasPostVenta> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface ITagsRepository : IRepository<Tags> { }

	public partial class TagsRepository : Repository<Tags>
	{
		public TagsRepository(IDbContext dbContext, ISqlMapper<Tags> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IPreciosFormulasRepository : IRepository<PreciosFormulas> { }

	public partial class PreciosFormulasRepository : Repository<PreciosFormulas>
	{
		public PreciosFormulasRepository(IDbContext dbContext, ISqlMapper<PreciosFormulas> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IMLSettingsRepository : IRepository<MLSettings> { }

	public partial class MLSettingsRepository : Repository<MLSettings>
	{
		public MLSettingsRepository(IDbContext dbContext, ISqlMapper<MLSettings> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IBaseInformesRepository : IRepository<BaseInformes> { }

	public partial class BaseInformesRepository : Repository<BaseInformes>
	{
		public BaseInformesRepository(IDbContext dbContext, ISqlMapper<BaseInformes> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IPresupuestoRepository : IRepository<Presupuesto> { }

	public partial class PresupuestoRepository : Repository<Presupuesto>
	{
		public PresupuestoRepository(IDbContext dbContext, ISqlMapper<Presupuesto> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IViajanteRepository : IRepository<Viajante> { }

	public partial class ViajanteRepository : Repository<Viajante>
	{
		public ViajanteRepository(IDbContext dbContext, ISqlMapper<Viajante> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IWebArticulosComplementariosRepository : IRepository<WebArticulosComplementarios> { }

	public partial class WebArticulosComplementariosRepository : Repository<WebArticulosComplementarios>
	{
		public WebArticulosComplementariosRepository(IDbContext dbContext, ISqlMapper<WebArticulosComplementarios> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IWebMenuRepository : IRepository<WebMenu> { }

	public partial class WebMenuRepository : Repository<WebMenu>
	{
		public WebMenuRepository(IDbContext dbContext, ISqlMapper<WebMenu> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IBancosRepository : IRepository<Bancos> { }

	public partial class BancosRepository : Repository<Bancos>
	{
		public BancosRepository(IDbContext dbContext, ISqlMapper<Bancos> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IProveedoresCtaCteIdRepository : IRepository<ProveedoresCtaCteId> { }

	public partial class ProveedoresCtaCteIdRepository : Repository<ProveedoresCtaCteId>
	{
		public ProveedoresCtaCteIdRepository(IDbContext dbContext, ISqlMapper<ProveedoresCtaCteId> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IAuditoriaRepository : IRepository<Auditoria> { }

	public partial class AuditoriaRepository : Repository<Auditoria>
	{
		public AuditoriaRepository(IDbContext dbContext, ISqlMapper<Auditoria> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IWebSEORepository : IRepository<WebSEO> { }

	public partial class WebSEORepository : Repository<WebSEO>
	{
		public WebSEORepository(IDbContext dbContext, ISqlMapper<WebSEO> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IListasDePreciosRepository : IRepository<ListasDePrecios> { }

	public partial class ListasDePreciosRepository : Repository<ListasDePrecios>
	{
		public ListasDePreciosRepository(IDbContext dbContext, ISqlMapper<ListasDePrecios> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface ITipoClienteRepository : IRepository<TipoCliente> { }

	public partial class TipoClienteRepository : Repository<TipoCliente>
	{
		public TipoClienteRepository(IDbContext dbContext, ISqlMapper<TipoCliente> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IUsadosRepository : IRepository<Usados> { }

	public partial class UsadosRepository : Repository<Usados>
	{
		public UsadosRepository(IDbContext dbContext, ISqlMapper<Usados> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IRubroFamiliaRepository : IRepository<RubroFamilia> { }

	public partial class RubroFamiliaRepository : Repository<RubroFamilia>
	{
		public RubroFamiliaRepository(IDbContext dbContext, ISqlMapper<RubroFamilia> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IPreciosRepository : IRepository<Precios> { }

	public partial class PreciosRepository : Repository<Precios>
	{
		public PreciosRepository(IDbContext dbContext, ISqlMapper<Precios> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IAccesosRepository : IRepository<Accesos> { }

	public partial class AccesosRepository : Repository<Accesos>
	{
		public AccesosRepository(IDbContext dbContext, ISqlMapper<Accesos> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IAutorizacionCreditoRepository : IRepository<AutorizacionCredito> { }

	public partial class AutorizacionCreditoRepository : Repository<AutorizacionCredito>
	{
		public AutorizacionCreditoRepository(IDbContext dbContext, ISqlMapper<AutorizacionCredito> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IRubroRelacionFamiliaRepository : IRepository<RubroRelacionFamilia> { }

	public partial class RubroRelacionFamiliaRepository : Repository<RubroRelacionFamilia>
	{
		public RubroRelacionFamiliaRepository(IDbContext dbContext, ISqlMapper<RubroRelacionFamilia> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IStocksDisponiblesRepository : IRepository<StocksDisponibles> { }

	public partial class StocksDisponiblesRepository : Repository<StocksDisponibles>
	{
		public StocksDisponiblesRepository(IDbContext dbContext, ISqlMapper<StocksDisponibles> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IClienteComercioEventosRepository : IRepository<ClienteComercioEventos> { }

	public partial class ClienteComercioEventosRepository : Repository<ClienteComercioEventos>
	{
		public ClienteComercioEventosRepository(IDbContext dbContext, ISqlMapper<ClienteComercioEventos> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IVistaArticulosRepository : IRepository<VistaArticulos> { }

	public partial class VistaArticulosRepository : Repository<VistaArticulos>
	{
		public VistaArticulosRepository(IDbContext dbContext, ISqlMapper<VistaArticulos> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IArticuloComprobanteRepository : IRepository<ArticuloComprobante> { }

	public partial class ArticuloComprobanteRepository : Repository<ArticuloComprobante>
	{
		public ArticuloComprobanteRepository(IDbContext dbContext, ISqlMapper<ArticuloComprobante> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IRubrosGruposViewRepository : IRepository<RubrosGruposView> { }

	public partial class RubrosGruposViewRepository : Repository<RubrosGruposView>
	{
		public RubrosGruposViewRepository(IDbContext dbContext, ISqlMapper<RubrosGruposView> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IRubroRelacionGrupoRepository : IRepository<RubroRelacionGrupo> { }

	public partial class RubroRelacionGrupoRepository : Repository<RubroRelacionGrupo>
	{
		public RubroRelacionGrupoRepository(IDbContext dbContext, ISqlMapper<RubroRelacionGrupo> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IVistaArticulosVendidosRepository : IRepository<VistaArticulosVendidos> { }

	public partial class VistaArticulosVendidosRepository : Repository<VistaArticulosVendidos>
	{
		public VistaArticulosVendidosRepository(IDbContext dbContext, ISqlMapper<VistaArticulosVendidos> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IProveedoresCtaCteVencimientosRepository : IRepository<ProveedoresCtaCteVencimientos> { }

	public partial class ProveedoresCtaCteVencimientosRepository : Repository<ProveedoresCtaCteVencimientos>
	{
		public ProveedoresCtaCteVencimientosRepository(IDbContext dbContext, ISqlMapper<ProveedoresCtaCteVencimientos> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IComisionTipoRepository : IRepository<ComisionTipo> { }

	public partial class ComisionTipoRepository : Repository<ComisionTipo>
	{
		public ComisionTipoRepository(IDbContext dbContext, ISqlMapper<ComisionTipo> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IVistaClientesPublicoRepository : IRepository<VistaClientesPublico> { }

	public partial class VistaClientesPublicoRepository : Repository<VistaClientesPublico>
	{
		public VistaClientesPublicoRepository(IDbContext dbContext, ISqlMapper<VistaClientesPublico> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IMLFailingItemsRepository : IRepository<MLFailingItems> { }

	public partial class MLFailingItemsRepository : Repository<MLFailingItems>
	{
		public MLFailingItemsRepository(IDbContext dbContext, ISqlMapper<MLFailingItems> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IGroupedImagesRepository : IRepository<GroupedImages> { }

	public partial class GroupedImagesRepository : Repository<GroupedImages>
	{
		public GroupedImagesRepository(IDbContext dbContext, ISqlMapper<GroupedImages> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IArticuloComprobanteCantidadRepository : IRepository<ArticuloComprobanteCantidad> { }

	public partial class ArticuloComprobanteCantidadRepository : Repository<ArticuloComprobanteCantidad>
	{
		public ArticuloComprobanteCantidadRepository(IDbContext dbContext, ISqlMapper<ArticuloComprobanteCantidad> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IProveedorCtaCtePreSaldosRepository : IRepository<ProveedorCtaCtePreSaldos> { }

	public partial class ProveedorCtaCtePreSaldosRepository : Repository<ProveedorCtaCtePreSaldos>
	{
		public ProveedorCtaCtePreSaldosRepository(IDbContext dbContext, ISqlMapper<ProveedorCtaCtePreSaldos> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IComisionSubtipoRepository : IRepository<ComisionSubtipo> { }

	public partial class ComisionSubtipoRepository : Repository<ComisionSubtipo>
	{
		public ComisionSubtipoRepository(IDbContext dbContext, ISqlMapper<ComisionSubtipo> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IPersonaRepository : IRepository<Persona> { }

	public partial class PersonaRepository : Repository<Persona>
	{
		public PersonaRepository(IDbContext dbContext, ISqlMapper<Persona> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IVistaComprobantesRepository : IRepository<VistaComprobantes> { }

	public partial class VistaComprobantesRepository : Repository<VistaComprobantes>
	{
		public VistaComprobantesRepository(IDbContext dbContext, ISqlMapper<VistaComprobantes> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IProveedorCtaCteSaldosRepository : IRepository<ProveedorCtaCteSaldos> { }

	public partial class ProveedorCtaCteSaldosRepository : Repository<ProveedorCtaCteSaldos>
	{
		public ProveedorCtaCteSaldosRepository(IDbContext dbContext, ISqlMapper<ProveedorCtaCteSaldos> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IPersonaRelacionesRepository : IRepository<PersonaRelaciones> { }

	public partial class PersonaRelacionesRepository : Repository<PersonaRelaciones>
	{
		public PersonaRelacionesRepository(IDbContext dbContext, ISqlMapper<PersonaRelaciones> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IVistaComprobantesItemsRepository : IRepository<VistaComprobantesItems> { }

	public partial class VistaComprobantesItemsRepository : Repository<VistaComprobantesItems>
	{
		public VistaComprobantesItemsRepository(IDbContext dbContext, ISqlMapper<VistaComprobantesItems> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IComisionUsuarioRepository : IRepository<ComisionUsuario> { }

	public partial class ComisionUsuarioRepository : Repository<ComisionUsuario>
	{
		public ComisionUsuarioRepository(IDbContext dbContext, ISqlMapper<ComisionUsuario> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IStockProveedorRepository : IRepository<StockProveedor> { }

	public partial class StockProveedorRepository : Repository<StockProveedor>
	{
		public StockProveedorRepository(IDbContext dbContext, ISqlMapper<StockProveedor> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IVistaComprobantesItemsEncabezadoRepository : IRepository<VistaComprobantesItemsEncabezado> { }

	public partial class VistaComprobantesItemsEncabezadoRepository : Repository<VistaComprobantesItemsEncabezado>
	{
		public VistaComprobantesItemsEncabezadoRepository(IDbContext dbContext, ISqlMapper<VistaComprobantesItemsEncabezado> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IExclusionRetencionesPercepcionesRepository : IRepository<ExclusionRetencionesPercepciones> { }

	public partial class ExclusionRetencionesPercepcionesRepository : Repository<ExclusionRetencionesPercepciones>
	{
		public ExclusionRetencionesPercepcionesRepository(IDbContext dbContext, ISqlMapper<ExclusionRetencionesPercepciones> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface ITarjetasPagosRepository : IRepository<TarjetasPagos> { }

	public partial class TarjetasPagosRepository : Repository<TarjetasPagos>
	{
		public TarjetasPagosRepository(IDbContext dbContext, ISqlMapper<TarjetasPagos> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IVistaReciboRepository : IRepository<VistaRecibo> { }

	public partial class VistaReciboRepository : Repository<VistaRecibo>
	{
		public VistaReciboRepository(IDbContext dbContext, ISqlMapper<VistaRecibo> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface ITablaImpuestosRepository : IRepository<TablaImpuestos> { }

	public partial class TablaImpuestosRepository : Repository<TablaImpuestos>
	{
		public TablaImpuestosRepository(IDbContext dbContext, ISqlMapper<TablaImpuestos> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IComisionUsuarioSucursalRepository : IRepository<ComisionUsuarioSucursal> { }

	public partial class ComisionUsuarioSucursalRepository : Repository<ComisionUsuarioSucursal>
	{
		public ComisionUsuarioSucursalRepository(IDbContext dbContext, ISqlMapper<ComisionUsuarioSucursal> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IVistaExcelVentasRepository : IRepository<VistaExcelVentas> { }

	public partial class VistaExcelVentasRepository : Repository<VistaExcelVentas>
	{
		public VistaExcelVentasRepository(IDbContext dbContext, ISqlMapper<VistaExcelVentas> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IOrdenDeTrasladoRepository : IRepository<OrdenDeTraslado> { }

	public partial class OrdenDeTrasladoRepository : Repository<OrdenDeTraslado>
	{
		public OrdenDeTrasladoRepository(IDbContext dbContext, ISqlMapper<OrdenDeTraslado> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IImpuestoGananciaRepository : IRepository<ImpuestoGanancia> { }

	public partial class ImpuestoGananciaRepository : Repository<ImpuestoGanancia>
	{
		public ImpuestoGananciaRepository(IDbContext dbContext, ISqlMapper<ImpuestoGanancia> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IVistaInventarioEncabezadoRepository : IRepository<VistaInventarioEncabezado> { }

	public partial class VistaInventarioEncabezadoRepository : Repository<VistaInventarioEncabezado>
	{
		public VistaInventarioEncabezadoRepository(IDbContext dbContext, ISqlMapper<VistaInventarioEncabezado> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IVistaPagosRepository : IRepository<VistaPagos> { }

	public partial class VistaPagosRepository : Repository<VistaPagos>
	{
		public VistaPagosRepository(IDbContext dbContext, ISqlMapper<VistaPagos> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IMLCustomFiltersRepository : IRepository<MLCustomFilters> { }

	public partial class MLCustomFiltersRepository : Repository<MLCustomFilters>
	{
		public MLCustomFiltersRepository(IDbContext dbContext, ISqlMapper<MLCustomFilters> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IInformeVentasEvolucionRepository : IRepository<InformeVentasEvolucion> { }

	public partial class InformeVentasEvolucionRepository : Repository<InformeVentasEvolucion>
	{
		public InformeVentasEvolucionRepository(IDbContext dbContext, ISqlMapper<InformeVentasEvolucion> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IBancosSucursalRepository : IRepository<BancosSucursal> { }

	public partial class BancosSucursalRepository : Repository<BancosSucursal>
	{
		public BancosSucursalRepository(IDbContext dbContext, ISqlMapper<BancosSucursal> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IMedidasRepository : IRepository<Medidas> { }

	public partial class MedidasRepository : Repository<Medidas>
	{
		public MedidasRepository(IDbContext dbContext, ISqlMapper<Medidas> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IVistaProveedoresPedidoRepository : IRepository<VistaProveedoresPedido> { }

	public partial class VistaProveedoresPedidoRepository : Repository<VistaProveedoresPedido>
	{
		public VistaProveedoresPedidoRepository(IDbContext dbContext, ISqlMapper<VistaProveedoresPedido> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IUsuariosNotificacionesRepository : IRepository<UsuariosNotificaciones> { }

	public partial class UsuariosNotificacionesRepository : Repository<UsuariosNotificaciones>
	{
		public UsuariosNotificacionesRepository(IDbContext dbContext, ISqlMapper<UsuariosNotificaciones> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IVistaRemitoTercerizadoRepository : IRepository<VistaRemitoTercerizado> { }

	public partial class VistaRemitoTercerizadoRepository : Repository<VistaRemitoTercerizado>
	{
		public VistaRemitoTercerizadoRepository(IDbContext dbContext, ISqlMapper<VistaRemitoTercerizado> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IMPOrdenesRepository : IRepository<MPOrdenes> { }

	public partial class MPOrdenesRepository : Repository<MPOrdenes>
	{
		public MPOrdenesRepository(IDbContext dbContext, ISqlMapper<MPOrdenes> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IServicioTecnicoInsumosRepository : IRepository<ServicioTecnicoInsumos> { }

	public partial class ServicioTecnicoInsumosRepository : Repository<ServicioTecnicoInsumos>
	{
		public ServicioTecnicoInsumosRepository(IDbContext dbContext, ISqlMapper<ServicioTecnicoInsumos> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IVistaRemitoTercerizadoItemRepository : IRepository<VistaRemitoTercerizadoItem> { }

	public partial class VistaRemitoTercerizadoItemRepository : Repository<VistaRemitoTercerizadoItem>
	{
		public VistaRemitoTercerizadoItemRepository(IDbContext dbContext, ISqlMapper<VistaRemitoTercerizadoItem> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface INumerosComprobantesRepository : IRepository<NumerosComprobantes> { }

	public partial class NumerosComprobantesRepository : Repository<NumerosComprobantes>
	{
		public NumerosComprobantesRepository(IDbContext dbContext, ISqlMapper<NumerosComprobantes> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IVistaItemsWebheavenbizb2bRepository : IRepository<VistaItemsWebheavenbizb2b> { }

	public partial class VistaItemsWebheavenbizb2bRepository : Repository<VistaItemsWebheavenbizb2b>
	{
		public VistaItemsWebheavenbizb2bRepository(IDbContext dbContext, ISqlMapper<VistaItemsWebheavenbizb2b> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IPagosRepository : IRepository<Pagos> { }

	public partial class PagosRepository : Repository<Pagos>
	{
		public PagosRepository(IDbContext dbContext, ISqlMapper<Pagos> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IRecibosRepository : IRepository<Recibos> { }

	public partial class RecibosRepository : Repository<Recibos>
	{
		public RecibosRepository(IDbContext dbContext, ISqlMapper<Recibos> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface ILibroDiarioRepository : IRepository<LibroDiario> { }

	public partial class LibroDiarioRepository : Repository<LibroDiario>
	{
		public LibroDiarioRepository(IDbContext dbContext, ISqlMapper<LibroDiario> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IVistaServicioTecnicoRepository : IRepository<VistaServicioTecnico> { }

	public partial class VistaServicioTecnicoRepository : Repository<VistaServicioTecnico>
	{
		public VistaServicioTecnicoRepository(IDbContext dbContext, ISqlMapper<VistaServicioTecnico> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IUsuariosCtaCteRepository : IRepository<UsuariosCtaCte> { }

	public partial class UsuariosCtaCteRepository : Repository<UsuariosCtaCte>
	{
		public UsuariosCtaCteRepository(IDbContext dbContext, ISqlMapper<UsuariosCtaCte> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IConfiguracionBusquedaArticulosRepository : IRepository<ConfiguracionBusquedaArticulos> { }

	public partial class ConfiguracionBusquedaArticulosRepository : Repository<ConfiguracionBusquedaArticulos>
	{
		public ConfiguracionBusquedaArticulosRepository(IDbContext dbContext, ISqlMapper<ConfiguracionBusquedaArticulos> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IPriceIncreaseTemplatesRepository : IRepository<PriceIncreaseTemplates> { }

	public partial class PriceIncreaseTemplatesRepository : Repository<PriceIncreaseTemplates>
	{
		public PriceIncreaseTemplatesRepository(IDbContext dbContext, ISqlMapper<PriceIncreaseTemplates> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IFotosOriginalesRepository : IRepository<FotosOriginales> { }

	public partial class FotosOriginalesRepository : Repository<FotosOriginales>
	{
		public FotosOriginalesRepository(IDbContext dbContext, ISqlMapper<FotosOriginales> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IProveedoresPorcentajesRepository : IRepository<ProveedoresPorcentajes> { }

	public partial class ProveedoresPorcentajesRepository : Repository<ProveedoresPorcentajes>
	{
		public ProveedoresPorcentajesRepository(IDbContext dbContext, ISqlMapper<ProveedoresPorcentajes> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IVistaTarjetasCarteraRepository : IRepository<VistaTarjetasCartera> { }

	public partial class VistaTarjetasCarteraRepository : Repository<VistaTarjetasCartera>
	{
		public VistaTarjetasCarteraRepository(IDbContext dbContext, ISqlMapper<VistaTarjetasCartera> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IPriceIncreaseListsRepository : IRepository<PriceIncreaseLists> { }

	public partial class PriceIncreaseListsRepository : Repository<PriceIncreaseLists>
	{
		public PriceIncreaseListsRepository(IDbContext dbContext, ISqlMapper<PriceIncreaseLists> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IInventarioEncabezadoRepository : IRepository<InventarioEncabezado> { }

	public partial class InventarioEncabezadoRepository : Repository<InventarioEncabezado>
	{
		public InventarioEncabezadoRepository(IDbContext dbContext, ISqlMapper<InventarioEncabezado> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IClientesComercioCtaCteRepository : IRepository<ClientesComercioCtaCte> { }

	public partial class ClientesComercioCtaCteRepository : Repository<ClientesComercioCtaCte>
	{
		public ClientesComercioCtaCteRepository(IDbContext dbContext, ISqlMapper<ClientesComercioCtaCte> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IVistaItemsWebhcRepository : IRepository<VistaItemsWebhc> { }

	public partial class VistaItemsWebhcRepository : Repository<VistaItemsWebhc>
	{
		public VistaItemsWebhcRepository(IDbContext dbContext, ISqlMapper<VistaItemsWebhc> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface ILibrosIVACerradosRepository : IRepository<LibrosIVACerrados> { }

	public partial class LibrosIVACerradosRepository : Repository<LibrosIVACerrados>
	{
		public LibrosIVACerradosRepository(IDbContext dbContext, ISqlMapper<LibrosIVACerrados> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface INovedadesDeLaGerenciaRepository : IRepository<NovedadesDeLaGerencia> { }

	public partial class NovedadesDeLaGerenciaRepository : Repository<NovedadesDeLaGerencia>
	{
		public NovedadesDeLaGerenciaRepository(IDbContext dbContext, ISqlMapper<NovedadesDeLaGerencia> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface ICotizacionDolarEnPesosRepository : IRepository<CotizacionDolarEnPesos> { }

	public partial class CotizacionDolarEnPesosRepository : Repository<CotizacionDolarEnPesos>
	{
		public CotizacionDolarEnPesosRepository(IDbContext dbContext, ISqlMapper<CotizacionDolarEnPesos> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface ICajaCajeroCierreRepository : IRepository<CajaCajeroCierre> { }

	public partial class CajaCajeroCierreRepository : Repository<CajaCajeroCierre>
	{
		public CajaCajeroCierreRepository(IDbContext dbContext, ISqlMapper<CajaCajeroCierre> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IArticulosProduccionRepository : IRepository<ArticulosProduccion> { }

	public partial class ArticulosProduccionRepository : Repository<ArticulosProduccion>
	{
		public ArticulosProduccionRepository(IDbContext dbContext, ISqlMapper<ArticulosProduccion> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IImagesRepository : IRepository<Images> { }

	public partial class ImagesRepository : Repository<Images>
	{
		public ImagesRepository(IDbContext dbContext, ISqlMapper<Images> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IClientesComercioRepository : IRepository<ClientesComercio> { }

	public partial class ClientesComercioRepository : Repository<ClientesComercio>
	{
		public ClientesComercioRepository(IDbContext dbContext, ISqlMapper<ClientesComercio> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IOrdenesEstadosRepository : IRepository<OrdenesEstados> { }

	public partial class OrdenesEstadosRepository : Repository<OrdenesEstados>
	{
		public OrdenesEstadosRepository(IDbContext dbContext, ISqlMapper<OrdenesEstados> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface ISitesRepository : IRepository<Sites> { }

	public partial class SitesRepository : Repository<Sites>
	{
		public SitesRepository(IDbContext dbContext, ISqlMapper<Sites> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IComprobantesItemsComentariosRepository : IRepository<ComprobantesItemsComentarios> { }

	public partial class ComprobantesItemsComentariosRepository : Repository<ComprobantesItemsComentarios>
	{
		public ComprobantesItemsComentariosRepository(IDbContext dbContext, ISqlMapper<ComprobantesItemsComentarios> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IRubrosRepository : IRepository<Rubros> { }

	public partial class RubrosRepository : Repository<Rubros>
	{
		public RubrosRepository(IDbContext dbContext, ISqlMapper<Rubros> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface ITransferenciasCtaCteRepository : IRepository<TransferenciasCtaCte> { }

	public partial class TransferenciasCtaCteRepository : Repository<TransferenciasCtaCte>
	{
		public TransferenciasCtaCteRepository(IDbContext dbContext, ISqlMapper<TransferenciasCtaCte> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IPlanesDeCobroRepository : IRepository<PlanesDeCobro> { }

	public partial class PlanesDeCobroRepository : Repository<PlanesDeCobro>
	{
		public PlanesDeCobroRepository(IDbContext dbContext, ISqlMapper<PlanesDeCobro> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface ITagsArticulosRepository : IRepository<TagsArticulos> { }

	public partial class TagsArticulosRepository : Repository<TagsArticulos>
	{
		public TagsArticulosRepository(IDbContext dbContext, ISqlMapper<TagsArticulos> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IChequesPropiosRepository : IRepository<ChequesPropios> { }

	public partial class ChequesPropiosRepository : Repository<ChequesPropios>
	{
		public ChequesPropiosRepository(IDbContext dbContext, ISqlMapper<ChequesPropios> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IPreciosPendientesRepository : IRepository<PreciosPendientes> { }

	public partial class PreciosPendientesRepository : Repository<PreciosPendientes>
	{
		public PreciosPendientesRepository(IDbContext dbContext, ISqlMapper<PreciosPendientes> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IServiciosDescuentoRepository : IRepository<ServiciosDescuento> { }

	public partial class ServiciosDescuentoRepository : Repository<ServiciosDescuento>
	{
		public ServiciosDescuentoRepository(IDbContext dbContext, ISqlMapper<ServiciosDescuento> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IClienteComerciosRelacionRepository : IRepository<ClienteComerciosRelacion> { }

	public partial class ClienteComerciosRelacionRepository : Repository<ClienteComerciosRelacion>
	{
		public ClienteComerciosRelacionRepository(IDbContext dbContext, ISqlMapper<ClienteComerciosRelacion> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IAgenteDeRetencionPercepcionRepository : IRepository<AgenteDeRetencionPercepcion> { }

	public partial class AgenteDeRetencionPercepcionRepository : Repository<AgenteDeRetencionPercepcion>
	{
		public AgenteDeRetencionPercepcionRepository(IDbContext dbContext, ISqlMapper<AgenteDeRetencionPercepcion> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IServiceTurnosRepository : IRepository<ServiceTurnos> { }

	public partial class ServiceTurnosRepository : Repository<ServiceTurnos>
	{
		public ServiceTurnosRepository(IDbContext dbContext, ISqlMapper<ServiceTurnos> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IMLArticulosRepository : IRepository<MLArticulos> { }

	public partial class MLArticulosRepository : Repository<MLArticulos>
	{
		public MLArticulosRepository(IDbContext dbContext, ISqlMapper<MLArticulos> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IClientePublicoLlamadoRepository : IRepository<ClientePublicoLlamado> { }

	public partial class ClientePublicoLlamadoRepository : Repository<ClientePublicoLlamado>
	{
		public ClientePublicoLlamadoRepository(IDbContext dbContext, ISqlMapper<ClientePublicoLlamado> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IPlanCuentasContableRepository : IRepository<PlanCuentasContable> { }

	public partial class PlanCuentasContableRepository : Repository<PlanCuentasContable>
	{
		public PlanCuentasContableRepository(IDbContext dbContext, ISqlMapper<PlanCuentasContable> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IClientesUsuarioRepository : IRepository<ClientesUsuario> { }

	public partial class ClientesUsuarioRepository : Repository<ClientesUsuario>
	{
		public ClientesUsuarioRepository(IDbContext dbContext, ISqlMapper<ClientesUsuario> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IClientesPorcentajesDescuentoRepository : IRepository<ClientesPorcentajesDescuento> { }

	public partial class ClientesPorcentajesDescuentoRepository : Repository<ClientesPorcentajesDescuento>
	{
		public ClientesPorcentajesDescuentoRepository(IDbContext dbContext, ISqlMapper<ClientesPorcentajesDescuento> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IStockRegistroVehiculoRepository : IRepository<StockRegistroVehiculo> { }

	public partial class StockRegistroVehiculoRepository : Repository<StockRegistroVehiculo>
	{
		public StockRegistroVehiculoRepository(IDbContext dbContext, ISqlMapper<StockRegistroVehiculo> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IMLUsuarioRepository : IRepository<MLUsuario> { }

	public partial class MLUsuarioRepository : Repository<MLUsuario>
	{
		public MLUsuarioRepository(IDbContext dbContext, ISqlMapper<MLUsuario> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IArticulosConsignacionRepository : IRepository<ArticulosConsignacion> { }

	public partial class ArticulosConsignacionRepository : Repository<ArticulosConsignacion>
	{
		public ArticulosConsignacionRepository(IDbContext dbContext, ISqlMapper<ArticulosConsignacion> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface ICajaCierresRepository : IRepository<CajaCierres> { }

	public partial class CajaCierresRepository : Repository<CajaCierres>
	{
		public CajaCierresRepository(IDbContext dbContext, ISqlMapper<CajaCierres> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface ICajaAsientosRepository : IRepository<CajaAsientos> { }

	public partial class CajaAsientosRepository : Repository<CajaAsientos>
	{
		public CajaAsientosRepository(IDbContext dbContext, ISqlMapper<CajaAsientos> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface ICajaNombreCuentasRepository : IRepository<CajaNombreCuentas> { }

	public partial class CajaNombreCuentasRepository : Repository<CajaNombreCuentas>
	{
		public CajaNombreCuentasRepository(IDbContext dbContext, ISqlMapper<CajaNombreCuentas> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IArticulosPaqueteRepository : IRepository<ArticulosPaquete> { }

	public partial class ArticulosPaqueteRepository : Repository<ArticulosPaquete>
	{
		public ArticulosPaqueteRepository(IDbContext dbContext, ISqlMapper<ArticulosPaquete> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface ISucursalesRepository : IRepository<Sucursales> { }

	public partial class SucursalesRepository : Repository<Sucursales>
	{
		public SucursalesRepository(IDbContext dbContext, ISqlMapper<Sucursales> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IMLVariacionesRepository : IRepository<MLVariaciones> { }

	public partial class MLVariacionesRepository : Repository<MLVariaciones>
	{
		public MLVariacionesRepository(IDbContext dbContext, ISqlMapper<MLVariaciones> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IVtexUsuariosRepository : IRepository<VtexUsuarios> { }

	public partial class VtexUsuariosRepository : Repository<VtexUsuarios>
	{
		public VtexUsuariosRepository(IDbContext dbContext, ISqlMapper<VtexUsuarios> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IArticulosProveedoresRemotaRepository : IRepository<ArticulosProveedoresRemota> { }

	public partial class ArticulosProveedoresRemotaRepository : Repository<ArticulosProveedoresRemota>
	{
		public ArticulosProveedoresRemotaRepository(IDbContext dbContext, ISqlMapper<ArticulosProveedoresRemota> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IMLPicturesRepository : IRepository<MLPictures> { }

	public partial class MLPicturesRepository : Repository<MLPictures>
	{
		public MLPicturesRepository(IDbContext dbContext, ISqlMapper<MLPictures> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IMLSeguimientoPreciosRepository : IRepository<MLSeguimientoPrecios> { }

	public partial class MLSeguimientoPreciosRepository : Repository<MLSeguimientoPrecios>
	{
		public MLSeguimientoPreciosRepository(IDbContext dbContext, ISqlMapper<MLSeguimientoPrecios> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IArticulosMedidasAlternativasRepository : IRepository<ArticulosMedidasAlternativas> { }

	public partial class ArticulosMedidasAlternativasRepository : Repository<ArticulosMedidasAlternativas>
	{
		public ArticulosMedidasAlternativasRepository(IDbContext dbContext, ISqlMapper<ArticulosMedidasAlternativas> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IConfiguracionFormularioFacturaRepository : IRepository<ConfiguracionFormularioFactura> { }

	public partial class ConfiguracionFormularioFacturaRepository : Repository<ConfiguracionFormularioFactura>
	{
		public ConfiguracionFormularioFacturaRepository(IDbContext dbContext, ISqlMapper<ConfiguracionFormularioFactura> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IMLImagesLibraryRepository : IRepository<MLImagesLibrary> { }

	public partial class MLImagesLibraryRepository : Repository<MLImagesLibrary>
	{
		public MLImagesLibraryRepository(IDbContext dbContext, ISqlMapper<MLImagesLibrary> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IGarantiasExtendidasOtorgadasRepository : IRepository<GarantiasExtendidasOtorgadas> { }

	public partial class GarantiasExtendidasOtorgadasRepository : Repository<GarantiasExtendidasOtorgadas>
	{
		public GarantiasExtendidasOtorgadasRepository(IDbContext dbContext, ISqlMapper<GarantiasExtendidasOtorgadas> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IDocumentosCtaCteRepository : IRepository<DocumentosCtaCte> { }

	public partial class DocumentosCtaCteRepository : Repository<DocumentosCtaCte>
	{
		public DocumentosCtaCteRepository(IDbContext dbContext, ISqlMapper<DocumentosCtaCte> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IImpuestoGananciaExtraRepository : IRepository<ImpuestoGananciaExtra> { }

	public partial class ImpuestoGananciaExtraRepository : Repository<ImpuestoGananciaExtra>
	{
		public ImpuestoGananciaExtraRepository(IDbContext dbContext, ISqlMapper<ImpuestoGananciaExtra> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IInventarioPaqueteRepository : IRepository<InventarioPaquete> { }

	public partial class InventarioPaqueteRepository : Repository<InventarioPaquete>
	{
		public InventarioPaqueteRepository(IDbContext dbContext, ISqlMapper<InventarioPaquete> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IMPPuntosDeVentaRepository : IRepository<MPPuntosDeVenta> { }

	public partial class MPPuntosDeVentaRepository : Repository<MPPuntosDeVenta>
	{
		public MPPuntosDeVentaRepository(IDbContext dbContext, ISqlMapper<MPPuntosDeVenta> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IAcopioRepository : IRepository<Acopio> { }

	public partial class AcopioRepository : Repository<Acopio>
	{
		public AcopioRepository(IDbContext dbContext, ISqlMapper<Acopio> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IUnidadesAlternativasRepository : IRepository<UnidadesAlternativas> { }

	public partial class UnidadesAlternativasRepository : Repository<UnidadesAlternativas>
	{
		public UnidadesAlternativasRepository(IDbContext dbContext, ISqlMapper<UnidadesAlternativas> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface ILibroIVARepository : IRepository<LibroIVA> { }

	public partial class LibroIVARepository : Repository<LibroIVA>
	{
		public LibroIVARepository(IDbContext dbContext, ISqlMapper<LibroIVA> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IUsuariosCtaCteTotalRepository : IRepository<UsuariosCtaCteTotal> { }

	public partial class UsuariosCtaCteTotalRepository : Repository<UsuariosCtaCteTotal>
	{
		public UsuariosCtaCteTotalRepository(IDbContext dbContext, ISqlMapper<UsuariosCtaCteTotal> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IAcopioItemsRepository : IRepository<AcopioItems> { }

	public partial class AcopioItemsRepository : Repository<AcopioItems>
	{
		public AcopioItemsRepository(IDbContext dbContext, ISqlMapper<AcopioItems> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IVtexRelacionesRepository : IRepository<VtexRelaciones> { }

	public partial class VtexRelacionesRepository : Repository<VtexRelaciones>
	{
		public VtexRelacionesRepository(IDbContext dbContext, ISqlMapper<VtexRelaciones> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IServicioTecnicoFotosRepository : IRepository<ServicioTecnicoFotos> { }

	public partial class ServicioTecnicoFotosRepository : Repository<ServicioTecnicoFotos>
	{
		public ServicioTecnicoFotosRepository(IDbContext dbContext, ISqlMapper<ServicioTecnicoFotos> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IClientesComercioCtaCteAcopioRepository : IRepository<ClientesComercioCtaCteAcopio> { }

	public partial class ClientesComercioCtaCteAcopioRepository : Repository<ClientesComercioCtaCteAcopio>
	{
		public ClientesComercioCtaCteAcopioRepository(IDbContext dbContext, ISqlMapper<ClientesComercioCtaCteAcopio> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IMLARespuestasRepository : IRepository<MLARespuestas> { }

	public partial class MLARespuestasRepository : Repository<MLARespuestas>
	{
		public MLARespuestasRepository(IDbContext dbContext, ISqlMapper<MLARespuestas> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IRedondeosPreciosRepository : IRepository<RedondeosPrecios> { }

	public partial class RedondeosPreciosRepository : Repository<RedondeosPrecios>
	{
		public RedondeosPreciosRepository(IDbContext dbContext, ISqlMapper<RedondeosPrecios> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IPrecioLetrasRepository : IRepository<PrecioLetras> { }

	public partial class PrecioLetrasRepository : Repository<PrecioLetras>
	{
		public PrecioLetrasRepository(IDbContext dbContext, ISqlMapper<PrecioLetras> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IVistaItemsWebb2b1Repository : IRepository<VistaItemsWebb2b1> { }

	public partial class VistaItemsWebb2b1Repository : Repository<VistaItemsWebb2b1>
	{
		public VistaItemsWebb2b1Repository(IDbContext dbContext, ISqlMapper<VistaItemsWebb2b1> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IVtexWHxSucursalRepository : IRepository<VtexWHxSucursal> { }

	public partial class VtexWHxSucursalRepository : Repository<VtexWHxSucursal>
	{
		public VtexWHxSucursalRepository(IDbContext dbContext, ISqlMapper<VtexWHxSucursal> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IGarantiasExtendidasCompaniasRepository : IRepository<GarantiasExtendidasCompanias> { }

	public partial class GarantiasExtendidasCompaniasRepository : Repository<GarantiasExtendidasCompanias>
	{
		public GarantiasExtendidasCompaniasRepository(IDbContext dbContext, ISqlMapper<GarantiasExtendidasCompanias> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IArticulosEventualesRepository : IRepository<ArticulosEventuales> { }

	public partial class ArticulosEventualesRepository : Repository<ArticulosEventuales>
	{
		public ArticulosEventualesRepository(IDbContext dbContext, ISqlMapper<ArticulosEventuales> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IMLEtiquetasOrdenRepository : IRepository<MLEtiquetasOrden> { }

	public partial class MLEtiquetasOrdenRepository : Repository<MLEtiquetasOrden>
	{
		public MLEtiquetasOrdenRepository(IDbContext dbContext, ISqlMapper<MLEtiquetasOrden> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IImportacionOtrosGastosRepository : IRepository<ImportacionOtrosGastos> { }

	public partial class ImportacionOtrosGastosRepository : Repository<ImportacionOtrosGastos>
	{
		public ImportacionOtrosGastosRepository(IDbContext dbContext, ISqlMapper<ImportacionOtrosGastos> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface ICajaAgrupacionRepository : IRepository<CajaAgrupacion> { }

	public partial class CajaAgrupacionRepository : Repository<CajaAgrupacion>
	{
		public CajaAgrupacionRepository(IDbContext dbContext, ISqlMapper<CajaAgrupacion> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IPaqueteUnArticuloComprobanteItemRepository : IRepository<PaqueteUnArticuloComprobanteItem> { }

	public partial class PaqueteUnArticuloComprobanteItemRepository : Repository<PaqueteUnArticuloComprobanteItem>
	{
		public PaqueteUnArticuloComprobanteItemRepository(IDbContext dbContext, ISqlMapper<PaqueteUnArticuloComprobanteItem> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IStockNumeroSerieRepository : IRepository<StockNumeroSerie> { }

	public partial class StockNumeroSerieRepository : Repository<StockNumeroSerie>
	{
		public StockNumeroSerieRepository(IDbContext dbContext, ISqlMapper<StockNumeroSerie> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IOrdenesEnviosRepository : IRepository<OrdenesEnvios> { }

	public partial class OrdenesEnviosRepository : Repository<OrdenesEnvios>
	{
		public OrdenesEnviosRepository(IDbContext dbContext, ISqlMapper<OrdenesEnvios> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IImportacionEncabezadoRepository : IRepository<ImportacionEncabezado> { }

	public partial class ImportacionEncabezadoRepository : Repository<ImportacionEncabezado>
	{
		public ImportacionEncabezadoRepository(IDbContext dbContext, ISqlMapper<ImportacionEncabezado> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IImportacionesItemsRepository : IRepository<ImportacionesItems> { }

	public partial class ImportacionesItemsRepository : Repository<ImportacionesItems>
	{
		public ImportacionesItemsRepository(IDbContext dbContext, ISqlMapper<ImportacionesItems> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IMarcasRepository : IRepository<Marcas> { }

	public partial class MarcasRepository : Repository<Marcas>
	{
		public MarcasRepository(IDbContext dbContext, ISqlMapper<Marcas> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IOrdenesRepository : IRepository<Ordenes> { }

	public partial class OrdenesRepository : Repository<Ordenes>
	{
		public OrdenesRepository(IDbContext dbContext, ISqlMapper<Ordenes> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IChequesTercerosRepository : IRepository<ChequesTerceros> { }

	public partial class ChequesTercerosRepository : Repository<ChequesTerceros>
	{
		public ChequesTercerosRepository(IDbContext dbContext, ISqlMapper<ChequesTerceros> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IStockDespachoTotalesRepository : IRepository<StockDespachoTotales> { }

	public partial class StockDespachoTotalesRepository : Repository<StockDespachoTotales>
	{
		public StockDespachoTotalesRepository(IDbContext dbContext, ISqlMapper<StockDespachoTotales> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IGarantiasExtendidasTipoDocumentoRepository : IRepository<GarantiasExtendidasTipoDocumento> { }

	public partial class GarantiasExtendidasTipoDocumentoRepository : Repository<GarantiasExtendidasTipoDocumento>
	{
		public GarantiasExtendidasTipoDocumentoRepository(IDbContext dbContext, ISqlMapper<GarantiasExtendidasTipoDocumento> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface ITablasTalleRepository : IRepository<TablasTalle> { }

	public partial class TablasTalleRepository : Repository<TablasTalle>
	{
		public TablasTalleRepository(IDbContext dbContext, ISqlMapper<TablasTalle> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface ITablasTalleItemsRepository : IRepository<TablasTalleItems> { }

	public partial class TablasTalleItemsRepository : Repository<TablasTalleItems>
	{
		public TablasTalleItemsRepository(IDbContext dbContext, ISqlMapper<TablasTalleItems> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IInventarioRepository : IRepository<Inventario> { }

	public partial class InventarioRepository : Repository<Inventario>
	{
		public InventarioRepository(IDbContext dbContext, ISqlMapper<Inventario> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IFotosPendientesSubidaRepository : IRepository<FotosPendientesSubida> { }

	public partial class FotosPendientesSubidaRepository : Repository<FotosPendientesSubida>
	{
		public FotosPendientesSubidaRepository(IDbContext dbContext, ISqlMapper<FotosPendientesSubida> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IGarantiasExtendidasPaisRepository : IRepository<GarantiasExtendidasPais> { }

	public partial class GarantiasExtendidasPaisRepository : Repository<GarantiasExtendidasPais>
	{
		public GarantiasExtendidasPaisRepository(IDbContext dbContext, ISqlMapper<GarantiasExtendidasPais> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IHondaContractRepository : IRepository<HondaContract> { }

	public partial class HondaContractRepository : Repository<HondaContract>
	{
		public HondaContractRepository(IDbContext dbContext, ISqlMapper<HondaContract> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IChequesPropiosDistribucionRepository : IRepository<ChequesPropiosDistribucion> { }

	public partial class ChequesPropiosDistribucionRepository : Repository<ChequesPropiosDistribucion>
	{
		public ChequesPropiosDistribucionRepository(IDbContext dbContext, ISqlMapper<ChequesPropiosDistribucion> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IDynamicReportRepository : IRepository<DynamicReport> { }

	public partial class DynamicReportRepository : Repository<DynamicReport>
	{
		public DynamicReportRepository(IDbContext dbContext, ISqlMapper<DynamicReport> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IProveedorLibreRepository : IRepository<ProveedorLibre> { }

	public partial class ProveedorLibreRepository : Repository<ProveedorLibre>
	{
		public ProveedorLibreRepository(IDbContext dbContext, ISqlMapper<ProveedorLibre> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IProveedoresCtaCteRepository : IRepository<ProveedoresCtaCte> { }

	public partial class ProveedoresCtaCteRepository : Repository<ProveedoresCtaCte>
	{
		public ProveedoresCtaCteRepository(IDbContext dbContext, ISqlMapper<ProveedoresCtaCte> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IDynamicReportBranchRepository : IRepository<DynamicReportBranch> { }

	public partial class DynamicReportBranchRepository : Repository<DynamicReportBranch>
	{
		public DynamicReportBranchRepository(IDbContext dbContext, ISqlMapper<DynamicReportBranch> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IArticulosRepository : IRepository<Articulos> { }

	public partial class ArticulosRepository : Repository<Articulos>
	{
		public ArticulosRepository(IDbContext dbContext, ISqlMapper<Articulos> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IDynamicReportUserRepository : IRepository<DynamicReportUser> { }

	public partial class DynamicReportUserRepository : Repository<DynamicReportUser>
	{
		public DynamicReportUserRepository(IDbContext dbContext, ISqlMapper<DynamicReportUser> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface ICanalesVentaRepository : IRepository<CanalesVenta> { }

	public partial class CanalesVentaRepository : Repository<CanalesVenta>
	{
		public CanalesVentaRepository(IDbContext dbContext, ISqlMapper<CanalesVenta> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IGarantiasExtendidasTipoComprobanteRepository : IRepository<GarantiasExtendidasTipoComprobante> { }

	public partial class GarantiasExtendidasTipoComprobanteRepository : Repository<GarantiasExtendidasTipoComprobante>
	{
		public GarantiasExtendidasTipoComprobanteRepository(IDbContext dbContext, ISqlMapper<GarantiasExtendidasTipoComprobante> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IDiarioPlanCuentaRepository : IRepository<DiarioPlanCuenta> { }

	public partial class DiarioPlanCuentaRepository : Repository<DiarioPlanCuenta>
	{
		public DiarioPlanCuentaRepository(IDbContext dbContext, ISqlMapper<DiarioPlanCuenta> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface ITamañoFotosRepository : IRepository<TamañoFotos> { }

	public partial class TamañoFotosRepository : Repository<TamañoFotos>
	{
		public TamañoFotosRepository(IDbContext dbContext, ISqlMapper<TamañoFotos> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IDynamicReportFilterRepository : IRepository<DynamicReportFilter> { }

	public partial class DynamicReportFilterRepository : Repository<DynamicReportFilter>
	{
		public DynamicReportFilterRepository(IDbContext dbContext, ISqlMapper<DynamicReportFilter> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IDynamicReportColumnRepository : IRepository<DynamicReportColumn> { }

	public partial class DynamicReportColumnRepository : Repository<DynamicReportColumn>
	{
		public DynamicReportColumnRepository(IDbContext dbContext, ISqlMapper<DynamicReportColumn> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IMLLogsRepository : IRepository<MLLogs> { }

	public partial class MLLogsRepository : Repository<MLLogs>
	{
		public MLLogsRepository(IDbContext dbContext, ISqlMapper<MLLogs> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IComprobantesAsociadosRepository : IRepository<ComprobantesAsociados> { }

	public partial class ComprobantesAsociadosRepository : Repository<ComprobantesAsociados>
	{
		public ComprobantesAsociadosRepository(IDbContext dbContext, ISqlMapper<ComprobantesAsociados> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface INumeroClienteEnProveedorRepository : IRepository<NumeroClienteEnProveedor> { }

	public partial class NumeroClienteEnProveedorRepository : Repository<NumeroClienteEnProveedor>
	{
		public NumeroClienteEnProveedorRepository(IDbContext dbContext, ISqlMapper<NumeroClienteEnProveedor> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IStockTotalesRepository : IRepository<StockTotales> { }

	public partial class StockTotalesRepository : Repository<StockTotales>
	{
		public StockTotalesRepository(IDbContext dbContext, ISqlMapper<StockTotales> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface ITrasladoArticulosRepository : IRepository<TrasladoArticulos> { }

	public partial class TrasladoArticulosRepository : Repository<TrasladoArticulos>
	{
		public TrasladoArticulosRepository(IDbContext dbContext, ISqlMapper<TrasladoArticulos> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IAuditoriaAccionRepository : IRepository<AuditoriaAccion> { }

	public partial class AuditoriaAccionRepository : Repository<AuditoriaAccion>
	{
		public AuditoriaAccionRepository(IDbContext dbContext, ISqlMapper<AuditoriaAccion> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IBaseInformesPeriodosRepository : IRepository<BaseInformesPeriodos> { }

	public partial class BaseInformesPeriodosRepository : Repository<BaseInformesPeriodos>
	{
		public BaseInformesPeriodosRepository(IDbContext dbContext, ISqlMapper<BaseInformesPeriodos> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IDepartamentosRepository : IRepository<Departamentos> { }

	public partial class DepartamentosRepository : Repository<Departamentos>
	{
		public DepartamentosRepository(IDbContext dbContext, ISqlMapper<Departamentos> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IArticuloDepartamentoRepository : IRepository<ArticuloDepartamento> { }

	public partial class ArticuloDepartamentoRepository : Repository<ArticuloDepartamento>
	{
		public ArticuloDepartamentoRepository(IDbContext dbContext, ISqlMapper<ArticuloDepartamento> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IUsuariosRepository : IRepository<Usuarios> { }

	public partial class UsuariosRepository : Repository<Usuarios>
	{
		public UsuariosRepository(IDbContext dbContext, ISqlMapper<Usuarios> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IProveedoresRepository : IRepository<Proveedores> { }

	public partial class ProveedoresRepository : Repository<Proveedores>
	{
		public ProveedoresRepository(IDbContext dbContext, ISqlMapper<Proveedores> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IEtiquetasRepository : IRepository<Etiquetas> { }

	public partial class EtiquetasRepository : Repository<Etiquetas>
	{
		public EtiquetasRepository(IDbContext dbContext, ISqlMapper<Etiquetas> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IMarcasActualizacionPreciosRepository : IRepository<MarcasActualizacionPrecios> { }

	public partial class MarcasActualizacionPreciosRepository : Repository<MarcasActualizacionPrecios>
	{
		public MarcasActualizacionPreciosRepository(IDbContext dbContext, ISqlMapper<MarcasActualizacionPrecios> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IStockMinimoMaximoRepository : IRepository<StockMinimoMaximo> { }

	public partial class StockMinimoMaximoRepository : Repository<StockMinimoMaximo>
	{
		public StockMinimoMaximoRepository(IDbContext dbContext, ISqlMapper<StockMinimoMaximo> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface ICajaTransferenciaRepository : IRepository<CajaTransferencia> { }

	public partial class CajaTransferenciaRepository : Repository<CajaTransferencia>
	{
		public CajaTransferenciaRepository(IDbContext dbContext, ISqlMapper<CajaTransferencia> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IFormasPagoHabilitadasRepository : IRepository<FormasPagoHabilitadas> { }

	public partial class FormasPagoHabilitadasRepository : Repository<FormasPagoHabilitadas>
	{
		public FormasPagoHabilitadasRepository(IDbContext dbContext, ISqlMapper<FormasPagoHabilitadas> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface ISenasRepository : IRepository<Senas> { }

	public partial class SenasRepository : Repository<Senas>
	{
		public SenasRepository(IDbContext dbContext, ISqlMapper<Senas> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface ITareasRepository : IRepository<Tareas> { }

	public partial class TareasRepository : Repository<Tareas>
	{
		public TareasRepository(IDbContext dbContext, ISqlMapper<Tareas> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IPromocionesPorArticuloRepository : IRepository<PromocionesPorArticulo> { }

	public partial class PromocionesPorArticuloRepository : Repository<PromocionesPorArticulo>
	{
		public PromocionesPorArticuloRepository(IDbContext dbContext, ISqlMapper<PromocionesPorArticulo> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IProveedorFacturaItemsRepository : IRepository<ProveedorFacturaItems> { }

	public partial class ProveedorFacturaItemsRepository : Repository<ProveedorFacturaItems>
	{
		public ProveedorFacturaItemsRepository(IDbContext dbContext, ISqlMapper<ProveedorFacturaItems> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IUsuariosHoraRepository : IRepository<UsuariosHora> { }

	public partial class UsuariosHoraRepository : Repository<UsuariosHora>
	{
		public UsuariosHoraRepository(IDbContext dbContext, ISqlMapper<UsuariosHora> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IClientesPublicoRepository : IRepository<ClientesPublico> { }

	public partial class ClientesPublicoRepository : Repository<ClientesPublico>
	{
		public ClientesPublicoRepository(IDbContext dbContext, ISqlMapper<ClientesPublico> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IComprobantesItemsRepository : IRepository<ComprobantesItems> { }

	public partial class ComprobantesItemsRepository : Repository<ComprobantesItems>
	{
		public ComprobantesItemsRepository(IDbContext dbContext, ISqlMapper<ComprobantesItems> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IServiciosRepository : IRepository<Servicios> { }

	public partial class ServiciosRepository : Repository<Servicios>
	{
		public ServiciosRepository(IDbContext dbContext, ISqlMapper<Servicios> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IProyectosRepository : IRepository<Proyectos> { }

	public partial class ProyectosRepository : Repository<Proyectos>
	{
		public ProyectosRepository(IDbContext dbContext, ISqlMapper<Proyectos> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IBancosAsientosRepository : IRepository<BancosAsientos> { }

	public partial class BancosAsientosRepository : Repository<BancosAsientos>
	{
		public BancosAsientosRepository(IDbContext dbContext, ISqlMapper<BancosAsientos> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IStockMovimientoRepository : IRepository<StockMovimiento> { }

	public partial class StockMovimientoRepository : Repository<StockMovimiento>
	{
		public StockMovimientoRepository(IDbContext dbContext, ISqlMapper<StockMovimiento> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IProveedorFacturaEncabezadoRepository : IRepository<ProveedorFacturaEncabezado> { }

	public partial class ProveedorFacturaEncabezadoRepository : Repository<ProveedorFacturaEncabezado>
	{
		public ProveedorFacturaEncabezadoRepository(IDbContext dbContext, ISqlMapper<ProveedorFacturaEncabezado> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IMLExpedicionesEncabezadosRepository : IRepository<MLExpedicionesEncabezados> { }

	public partial class MLExpedicionesEncabezadosRepository : Repository<MLExpedicionesEncabezados>
	{
		public MLExpedicionesEncabezadosRepository(IDbContext dbContext, ISqlMapper<MLExpedicionesEncabezados> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IFormaFormulariosRepository : IRepository<FormaFormularios> { }

	public partial class FormaFormulariosRepository : Repository<FormaFormularios>
	{
		public FormaFormulariosRepository(IDbContext dbContext, ISqlMapper<FormaFormularios> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IServicioTecnicoFechasRepository : IRepository<ServicioTecnicoFechas> { }

	public partial class ServicioTecnicoFechasRepository : Repository<ServicioTecnicoFechas>
	{
		public ServicioTecnicoFechasRepository(IDbContext dbContext, ISqlMapper<ServicioTecnicoFechas> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IMLExpedicionesRepository : IRepository<MLExpediciones> { }

	public partial class MLExpedicionesRepository : Repository<MLExpediciones>
	{
		public MLExpedicionesRepository(IDbContext dbContext, ISqlMapper<MLExpediciones> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IDetalleImpuestosRepository : IRepository<DetalleImpuestos> { }

	public partial class DetalleImpuestosRepository : Repository<DetalleImpuestos>
	{
		public DetalleImpuestosRepository(IDbContext dbContext, ISqlMapper<DetalleImpuestos> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IMLConfigImagesRepository : IRepository<MLConfigImages> { }

	public partial class MLConfigImagesRepository : Repository<MLConfigImages>
	{
		public MLConfigImagesRepository(IDbContext dbContext, ISqlMapper<MLConfigImages> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IServiciosImporteRepository : IRepository<ServiciosImporte> { }

	public partial class ServiciosImporteRepository : Repository<ServiciosImporte>
	{
		public ServiciosImporteRepository(IDbContext dbContext, ISqlMapper<ServiciosImporte> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IVtexMarcasRepository : IRepository<VtexMarcas> { }

	public partial class VtexMarcasRepository : Repository<VtexMarcas>
	{
		public VtexMarcasRepository(IDbContext dbContext, ISqlMapper<VtexMarcas> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IVtexCategoriasRepository : IRepository<VtexCategorias> { }

	public partial class VtexCategoriasRepository : Repository<VtexCategorias>
	{
		public VtexCategoriasRepository(IDbContext dbContext, ISqlMapper<VtexCategorias> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IClientesOcultosEnComprobantesRepository : IRepository<ClientesOcultosEnComprobantes> { }

	public partial class ClientesOcultosEnComprobantesRepository : Repository<ClientesOcultosEnComprobantes>
	{
		public ClientesOcultosEnComprobantesRepository(IDbContext dbContext, ISqlMapper<ClientesOcultosEnComprobantes> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IVtexOrdenesFacturadasRepository : IRepository<VtexOrdenesFacturadas> { }

	public partial class VtexOrdenesFacturadasRepository : Repository<VtexOrdenesFacturadas>
	{
		public VtexOrdenesFacturadasRepository(IDbContext dbContext, ISqlMapper<VtexOrdenesFacturadas> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IServicioTecnicoPaqueteRepository : IRepository<ServicioTecnicoPaquete> { }

	public partial class ServicioTecnicoPaqueteRepository : Repository<ServicioTecnicoPaquete>
	{
		public ServicioTecnicoPaqueteRepository(IDbContext dbContext, ISqlMapper<ServicioTecnicoPaquete> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IMLExtraInfoRepository : IRepository<MLExtraInfo> { }

	public partial class MLExtraInfoRepository : Repository<MLExtraInfo>
	{
		public MLExtraInfoRepository(IDbContext dbContext, ISqlMapper<MLExtraInfo> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface ITarjetasSucursalRepository : IRepository<TarjetasSucursal> { }

	public partial class TarjetasSucursalRepository : Repository<TarjetasSucursal>
	{
		public TarjetasSucursalRepository(IDbContext dbContext, ISqlMapper<TarjetasSucursal> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IOrdenesEnviosRelacionRepository : IRepository<OrdenesEnviosRelacion> { }

	public partial class OrdenesEnviosRelacionRepository : Repository<OrdenesEnviosRelacion>
	{
		public OrdenesEnviosRelacionRepository(IDbContext dbContext, ISqlMapper<OrdenesEnviosRelacion> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IImportacionCtaCteRepository : IRepository<ImportacionCtaCte> { }

	public partial class ImportacionCtaCteRepository : Repository<ImportacionCtaCte>
	{
		public ImportacionCtaCteRepository(IDbContext dbContext, ISqlMapper<ImportacionCtaCte> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IServicioTecnicoTipoArticuloRepository : IRepository<ServicioTecnicoTipoArticulo> { }

	public partial class ServicioTecnicoTipoArticuloRepository : Repository<ServicioTecnicoTipoArticulo>
	{
		public ServicioTecnicoTipoArticuloRepository(IDbContext dbContext, ISqlMapper<ServicioTecnicoTipoArticulo> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IFormaDePagoRepository : IRepository<FormaDePago> { }

	public partial class FormaDePagoRepository : Repository<FormaDePago>
	{
		public FormaDePagoRepository(IDbContext dbContext, ISqlMapper<FormaDePago> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IGarantiasExtendidasProvinciasRepository : IRepository<GarantiasExtendidasProvincias> { }

	public partial class GarantiasExtendidasProvinciasRepository : Repository<GarantiasExtendidasProvincias>
	{
		public GarantiasExtendidasProvinciasRepository(IDbContext dbContext, ISqlMapper<GarantiasExtendidasProvincias> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IVistaArticulosConsignacionRepository : IRepository<VistaArticulosConsignacion> { }

	public partial class VistaArticulosConsignacionRepository : Repository<VistaArticulosConsignacion>
	{
		public VistaArticulosConsignacionRepository(IDbContext dbContext, ISqlMapper<VistaArticulosConsignacion> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface ISumasYSaldosAsientoManualRepository : IRepository<SumasYSaldosAsientoManual> { }

	public partial class SumasYSaldosAsientoManualRepository : Repository<SumasYSaldosAsientoManual>
	{
		public SumasYSaldosAsientoManualRepository(IDbContext dbContext, ISqlMapper<SumasYSaldosAsientoManual> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IVtexUpdatePendingRepository : IRepository<VtexUpdatePending> { }

	public partial class VtexUpdatePendingRepository : Repository<VtexUpdatePending>
	{
		public VtexUpdatePendingRepository(IDbContext dbContext, ISqlMapper<VtexUpdatePending> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IVistaItemsWebb2b10Repository : IRepository<VistaItemsWebb2b10> { }

	public partial class VistaItemsWebb2b10Repository : Repository<VistaItemsWebb2b10>
	{
		public VistaItemsWebb2b10Repository(IDbContext dbContext, ISqlMapper<VistaItemsWebb2b10> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IServicioTecnicoTipArtIdUsuarioRepository : IRepository<ServicioTecnicoTipArtIdUsuario> { }

	public partial class ServicioTecnicoTipArtIdUsuarioRepository : Repository<ServicioTecnicoTipArtIdUsuario>
	{
		public ServicioTecnicoTipArtIdUsuarioRepository(IDbContext dbContext, ISqlMapper<ServicioTecnicoTipArtIdUsuario> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface ISinonimosRepository : IRepository<Sinonimos> { }

	public partial class SinonimosRepository : Repository<Sinonimos>
	{
		public SinonimosRepository(IDbContext dbContext, ISqlMapper<Sinonimos> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IHondaBranchRepository : IRepository<HondaBranch> { }

	public partial class HondaBranchRepository : Repository<HondaBranch>
	{
		public HondaBranchRepository(IDbContext dbContext, ISqlMapper<HondaBranch> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IVtexFailingItemsRepository : IRepository<VtexFailingItems> { }

	public partial class VtexFailingItemsRepository : Repository<VtexFailingItems>
	{
		public VtexFailingItemsRepository(IDbContext dbContext, ISqlMapper<VtexFailingItems> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IServicioTecnicoTipoTrabajoRepository : IRepository<ServicioTecnicoTipoTrabajo> { }

	public partial class ServicioTecnicoTipoTrabajoRepository : Repository<ServicioTecnicoTipoTrabajo>
	{
		public ServicioTecnicoTipoTrabajoRepository(IDbContext dbContext, ISqlMapper<ServicioTecnicoTipoTrabajo> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IRemitosParcialesItemsRepository : IRepository<RemitosParcialesItems> { }

	public partial class RemitosParcialesItemsRepository : Repository<RemitosParcialesItems>
	{
		public RemitosParcialesItemsRepository(IDbContext dbContext, ISqlMapper<RemitosParcialesItems> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IProveedoresPedidoRepository : IRepository<ProveedoresPedido> { }

	public partial class ProveedoresPedidoRepository : Repository<ProveedoresPedido>
	{
		public ProveedoresPedidoRepository(IDbContext dbContext, ISqlMapper<ProveedoresPedido> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IServicioTecnicoPrecioRepository : IRepository<ServicioTecnicoPrecio> { }

	public partial class ServicioTecnicoPrecioRepository : Repository<ServicioTecnicoPrecio>
	{
		public ServicioTecnicoPrecioRepository(IDbContext dbContext, ISqlMapper<ServicioTecnicoPrecio> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface ISettingsGrillasRepository : IRepository<SettingsGrillas> { }

	public partial class SettingsGrillasRepository : Repository<SettingsGrillas>
	{
		public SettingsGrillasRepository(IDbContext dbContext, ISqlMapper<SettingsGrillas> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IVistaArticulosVendidosResumidoRepository : IRepository<VistaArticulosVendidosResumido> { }

	public partial class VistaArticulosVendidosResumidoRepository : Repository<VistaArticulosVendidosResumido>
	{
		public VistaArticulosVendidosResumidoRepository(IDbContext dbContext, ISqlMapper<VistaArticulosVendidosResumido> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IClientesComercioCtaCteIdRepository : IRepository<ClientesComercioCtaCteId> { }

	public partial class ClientesComercioCtaCteIdRepository : Repository<ClientesComercioCtaCteId>
	{
		public ClientesComercioCtaCteIdRepository(IDbContext dbContext, ISqlMapper<ClientesComercioCtaCteId> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IVistaBancosAsientosRepository : IRepository<VistaBancosAsientos> { }

	public partial class VistaBancosAsientosRepository : Repository<VistaBancosAsientos>
	{
		public VistaBancosAsientosRepository(IDbContext dbContext, ISqlMapper<VistaBancosAsientos> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IStocksRepository : IRepository<Stocks> { }

	public partial class StocksRepository : Repository<Stocks>
	{
		public StocksRepository(IDbContext dbContext, ISqlMapper<Stocks> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IListaPreciosEncabezadoRepository : IRepository<ListaPreciosEncabezado> { }

	public partial class ListaPreciosEncabezadoRepository : Repository<ListaPreciosEncabezado>
	{
		public ListaPreciosEncabezadoRepository(IDbContext dbContext, ISqlMapper<ListaPreciosEncabezado> sqlMapper) : base(dbContext, sqlMapper) { }
	}

	public partial interface IServicioTecnicoUsuariosRepository : IRepository<ServicioTecnicoUsuarios> { }

	public partial class ServicioTecnicoUsuariosRepository : Repository<ServicioTecnicoUsuarios>
	{
		public ServicioTecnicoUsuariosRepository(IDbContext dbContext, ISqlMapper<ServicioTecnicoUsuarios> sqlMapper) : base(dbContext, sqlMapper) { }
	}

}
